### ISSUE TITLE
Sep 21 Release seems broken, which in turns breaks circup since it can only handle the latest release

### ISSUE THREAD

**Issue by piotrb** [adafruit/CircuitPython_Community_Bundle#224] opened 2024-09-24 21:13 UTC
It seems the release was created, but no assets were uploaded, the action run looks like it failed

**Comment by tannewt** [comment] 2024-09-25 17:42
This has been fixed by the breaking library. The root cause is documented and discussed here: https://github.com/adafruit/circuitpython-build-tools/issues/120

**Closed by tannewt** 2024-09-25 17:42 UTC
